name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install rbenv and ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y rbenv
          rbenv init
          rbenv install 3.1.4
          rbenv global 3.1.4
          touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site